openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition.
  version: 1.0

servers:
  - url: 'http://example.org'

paths:
  '/ping':
    get:
      responses:
        '200':
          description: example description