openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition.
  version: 1.0

servers:
  - url: 'http://api.redoc.ly'

paths:
  '/ping/items?id=###':
    get:
      operationId: getUserProfileById
      summary: Example summary
      responses:
        '200':
          description: example description
