apiDefinitions:
  # new: ./syntetic/syntetic-1.yaml
  # anotherWithError: ./syntetic/syntetic-2.yaml
  # sample: ./syntetic/to_bundle/bundle.yaml
  simpleDefinition: ./syntetic/syntetic.yaml
  rebilly: ./openapi-directory/rebilly-full.yaml

registry:
  organization: ggg
  definition: hello
  definitionVersion: bla

lint:
  codeframes: on
  headers:
    - name: Client-Header
      value: sometestvalue
      regexp: api.redoc.ly/.*
    - name: Custom
      envVariable: TEST_VAR
      regexp: api.redoc.ly/.*
  rules:
    bundler: off
    debug-info: off

    parameterPartial: warning
    parameterWithAllOf: warning

    oas3-schema/parameter: off
    oas3-schema/external-docs:
      url: off

    reg-rule:
      level: warning
      rules:
        UrlsNotExample:
          on: OpenAPIServer.url
          not: true
          startsWith: https://api-sandbox
          message: 'Example servers should not be in api sandbox. God knows why.'
        ParameterNameStartCapital:
          on: OpenAPIParameter.name
          not: true
          regexp: 'q'
          message: 'Parameter names not be q'
        ExternalDocsHelpdesk:
          on: OpenAPIExternalDocumentation.url
          startsWith: docs.redoc.ly
          message: 'External docs must be only on internal helpdesk'
        OnlyOpensourceLicense:
          on: OpenAPILicense.name
          regexp: '^Rebilly$'
          message: 'Only one license can be used'

    path-param-exists: on
    operation-2xx-response: on
    unique-parameter-names: on
    no-unused-schemas: on
    operation-operationId-unique: on
    path-declarations-must-exist: on

    api-servers: on
    license-url: on
    no-extra-fields: off
    operation-description: off
    operation-operationId: off
    operation-tags: off
    provide-contact: off
    servers-no-trailing-slash: off
