apiDefinitions:
  sample: ./syntetic/to_bundle/bundle.yaml
  simpleDefinition: ./syntetic/syntetic.yaml
  rebilly: ./openapi-directory/rebilly-full.yaml

resolve:
  http:
    headers:
      - name: Client-Header
        value: sometestvalue
        matches: api.redoc.ly/.*
      - name: Custom
        envVariable: TEST_VAR
        matches: api.redoc.ly/.*

lint:
  codeframes: on
  rules:
    bundler: off
    debug-info: off

    parameterPartial: warning
    parameterWithAllOf: warning

    oas3-schema/parameter: off
    oas3-schema/external-docs:
      url: off

    string-matcher: off

    path-param-exists: on
    operation-2xx-response: on
    unique-parameter-names: on
    no-unused-schemas: on
    operation-operationId-unique: on
    path-declarations-must-exist: on

    api-servers: on
    license-url: on
    no-extra-fields: on
    operation-description: off
    operation-operationId: off
    operation-tags: off
    provide-contact: off
    servers-no-trailing-slash: off
