apiDefinitions:
  main: ./openapi.yaml

lint:
  rules: 
    info-description: off
    info-contact: off
    info-license: off
    info-license-url: off

    tag-description: off
    tags-alphabetical: warning

    no-server-example.com: off
    no-server-trailing-slash: off
    no-empty-servers: off

    parameter-description: off
    no-path-trailing-slash: off
    path-declaration-must-exist: off
    path-not-include-query: off
    path-parameters-defined: off
    operation-description: off
    operation-2xx-response: off
    operation-operationId-unique: off
    operation-operationId-valid-in-url: off
    operation-parameters-unique: off
    operation-tag-defined: off
    operation-security-defined: off
    operationId-valid-in-url: off
    operation-singular-tag: off

    no-example-value-and-externalValue: off
    
    no-unused-components: off
    no-unresolved-refs: off
    no-enum-type-mismatch: off

    boolean-parameter-prefixes: off
    paths-kebab-case: off
    spec: off
  