openapi: 3.0.2
info:
  title: Test Spec
  version: 0.0.0
paths:
  /pet/findByStatus:
    get:
      summary: Finds pets by Status
      responses:
        '200':
          description: example description
      tags:
        - xpets
  /pet:
    post:
      summary: Adds a new pet to the store
      responses:
        '200':
          description: example description
      tags:
        - xpets
  /store/inventory:
    get:
      summary: Returns pet inventories
      responses:
        '200':
          description: example description
      tags:
        - astore    
tags:
  - name: xpets
    description: Everything about your Pets
    externalDocs:
      url: http://docs.my-api.com/pet-operations.htm
  - name: astore
    description: Access to Petstore orders
    externalDocs:
      url: http://docs.my-api.com/store-orders.htm