openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

paths:
  /pet/findByStatus:
    get:
      responses:
        '200':
          description: example description
  /pet:
    post:
      responses:
        '200':
          description: example description
  /store/inventory:
    get:
      responses:
        '200':
          description: example description
tags:
  - name: pets
    description: Everything about your Pets
    externalDocs:
      url: http://docs.my-api.com/pet-operations.htm
  - name: store
    description: Access to Petstore orders
    externalDocs:
      url: http://docs.my-api.com/store-orders.htm