openapi: 3.0.2
info:
  title: nanana
  version: fafafa
  license:
    name: bla
  contact:
    name: Sergey
    email: knidarkness@gmail.com
paths:
  /api:
    get:
      parameters:
        - $ref: '#/components/parameters/parameter.name.yml'
      responses:
        '200':
          description: blbbbb
          content:
            application/json:
              schema:
                type: string
    post:
      parameters:
        - $ref: '#/components/parameters/parameter.name.yml'
      responses:
        '200':
          description: blbbbb
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    exist:
      $ref: '#/components/schemas/exist'
  parameters:
    parameter.name.yml:
      in: query
      required: true
      name: name
      description: A name paramteter
      schema:
        type: object
        properties:
          name:
            type: string
          noRef:
            $ref: 'bad.yaml#/does/not/exist'
