openapi: 3.0.2
info:
  title: nanana
  version: fafafa
  license:
    name: bla
  contact:
    name: Sergey
    email: knidarkness@gmail.com
paths:
  /api:
    get:
      $ref: ./operations/api/api-get.yaml
    post:
      $ref: ./operations/api/api-post.yaml
  /anotherApi:
    get:
      $ref: ./operations/anotherApi/api-get.yaml
    post:
      $ref: ./operations/anotherApi/api-post.yaml