openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

components:
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.

paths:
  '/ping':
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The user ID.
    get:
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: example description