openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0
  contact:
    name: Ivan Goncharov
    email: ivan@redoc.ly
  license:
    name: example
    url: example.org

servers:
  - url: 'http://example.org'

paths:
  user:
    parameters:
      - $ref: '#/components/parameters/example'
    get:
      operationId: userGet
      description: Get user
      responses:
        '200':
          description: example description
          content:
            application/json:
              schema:
                type: object
  project:
    get:
      operationId: projectGet
      description: Get project
      responses:
        '200':
          description: example description
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    JWT:
      description: >
        You can create a JSON Web Token (JWT) via our [JWT Session
        resource](https://rebilly.github.io/RebillyUserAPI/#tag/JWT-Session/paths/~1signin/post).

        Usage format: `Bearer <JWT>`
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    example:
      allOf:
        - name: bla
          in: query
          required: false
          schema:
            type: string
        - description: 12
    genericExample:
      name: example
      in: query
      required: true
      schema:
        type: string
blabla: 313
customerSupport:
  id: 12
  contact:
    name: Ivan Goncharov
    email: ivan@redoc.ly
defaultParameterSchema:
  type: string