openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition.
  version: 1.0

paths:
  '/ping':
    get:
      operationId: getPingById
      responses:
        '200':
          description: example description
  '/pong':
    get:
      operationId: getPongById
      responses:
        '200':
          description: example description